package user

const (
	SignedUp                = "successfully signed up"
	PasswordIsCorrect       = "password is correct"
	PasswordIsIncorrect     = "password is incorrect"
	FailedToComparePassword = "password is incorrect or user does not exist"
	FoundByUsername         = "user found by username"
	NotFoundByUsername      = "user not found by username"
	FoundByUserId           = "user found by user id"
	NotFoundByUserId        = "user not found by user id"
	FoundByUserSharedId     = "user found by user shared id"
	NotFoundByUserSharedId  = "user not found by user shared id"
	Updated                 = "user updated successfully"
	FetchedUserProfile      = "fetched user profile successfully"
	FetchedPhoneNumber      = "fetched user phone number successfully"
	UsernameExists          = "username exists"
	UpdatedUsername         = "username changed successfully"
	UpdatedPassword         = "password changed successfully"
	UpdatedPhoneNumber      = "phone number changed successfully"
	DeletedUser             = "user deleted successfully"
	AddedUserEmail          = "email added successfully"
	FailedToAddUserEmail    = "email already exists"
	FoundUserEmail          = "user email found"
	NotFoundUserEmail       = "user email not found"
	UpdatedUserPrimaryEmail = "primary email changed successfully"
	DeletedUserEmail        = "email deleted successfully"
	FailedToDeleteUserEmail = "email does not exist or is the primary email"
	FetchedUserPrimaryEmail = "fetched primary email successfully"
	FetchedUserActiveEmails = "fetched active emails successfully"
	FetchedUserOwnProfile   = "fetched own profile successfully"
)
