package user

const (
	SignUpSuccess              = "successfully signed up"
	IsPasswordCorrectSuccess   = "password is correct"
	IsPasswordCorrectFailed    = "password is incorrect or user does not exist"
	PasswordIsIncorrect        = "password is incorrect"
	FoundByUsernameSuccess     = "user found by username"
	FoundByUsernameFailed      = "user not found by username"
	FoundByUserIdSuccess       = "user found by user id"
	FoundByUserIdFailed        = "user not found by user id"
	FoundByUserSharedIdSuccess = "user found by user shared id"
	FoundByUserSharedIdFailed  = "user not found by user shared id"
	UpdatedSuccess             = "user updated successfully"
	GetProfileSuccess          = "fetched user profile successfully"
	GetPhoneNumbersSuccess     = "fetched user phone numbers successfully"
	UsernameExistsSuccess      = "username exists"
	ChangeUsernameSuccess      = "username changed successfully"
	ChangePasswordSuccess      = "password changed successfully"
	ChangePhoneNumberSuccess   = "phone number changed successfully"
	DeleteUserSuccess          = "user deleted successfully"
	AddEmailSuccess            = "email added successfully"
	AddEmailFailed             = "email already exists"
	DeleteEmailSuccess         = "email deleted successfully"
	DeleteEmailFailed          = "email does not exist or is the primary email"
	GetPrimaryEmailSuccess     = "fetched primary email successfully"
)
